export const PANEL_1_R_WIDTH = 214;
export const PANEL_2_R_WIDTH = 200;
export const PANEL_3_R_WIDTH = 160;
export const ROOT_R_WIDTH = 232;

export const VELOCITY_PRESSURE_CASES_WIDTH = 400;
export const VELOCITY_PRESSURE_FULL_PANEL_4_R_WIDTH = 114;
export const VELOCITY_PRESSURE_FULL_PANEL_5_R_WIDTH = 70;

export const CALC_OROGRAPHY_DIALOG_R_WIDTH = 108;
export const CALC_OROGRAPHY_DIALOG_R_WIDTH_M = 90;
