/**
 * Generated by Moaui DevTools
 * Created at 2024. 5. 2. 오전 11:25:34
 */

import React from 'react';
import Moaui from '@midasit-dev/moaui';
import { usePython } from './customHooks';

const App = () => {
	const {get, doPyMain } = usePython();
	const [nodeValue, setNodeValue] = React.useState('');

  React.useEffect(() => {
		//웹페이지가 열릴 때, 동작을 정의 합니다.
		document.addEventListener('click', (e) => {
			//웹페이지가 열리고 클릭 이벤트가 발생할 때 마다 아래 로직이 실행 됩니다.
			const target = e.target as HTMLElement;
			//조건문을 아래에 추가 합니다.
			if (target.id === 'button_post') {
        doPyMain('post', get('input_id'), get('input_x'), get('input_y'), get('input_z'));
      }
      if (target.id === 'button_put') {
        doPyMain('put', get('input_id'), get('input_x'), get('input_y'), get('input_z'));
      }
      if (target.id === 'button_delete') {
        doPyMain('delete', get('input_id'));
      }
      if (target.id === 'button_get') {
        const data = doPyMain('get');
        setNodeValue(data);
      }
		})
	}, [get, doPyMain]);

	return (
		<Moaui.Panel variant='box' relative width={640} height={640}>
			<Moaui.FloatingBox {...{x: 0,y: 0,width: 328,height: 256,guideBoxProps: {"width":"inherit","height":"inherit","center":true,"spacing":2},}}>
				<Moaui.TextFieldV2 {...{id: 'input_id',autoFocus: false,type: 'text',placeholder: 'Placeholder',title: 'ID',titlePosition: 'left',error: false,disabled: false,width: '150px',titleXs: 3,inputXs: 9,height: '30px',textAlign: 'left',multiline: false,rows: 1,maxRows: 1,gap: 1,inputAlign: 'left',singleLineTitle: false,}}>
				</Moaui.TextFieldV2>
				<Moaui.TextFieldV2 {...{id: 'input_x',autoFocus: false,type: 'text',placeholder: 'Placeholder',title: 'X',titlePosition: 'left',error: false,disabled: false,width: '150px',titleXs: 3,inputXs: 9,height: '30px',textAlign: 'left',multiline: false,rows: 1,maxRows: 1,gap: 1,inputAlign: 'left',singleLineTitle: false,}}>
				</Moaui.TextFieldV2>
				<Moaui.TextFieldV2 {...{id: 'input_y',autoFocus: false,type: 'text',placeholder: 'Placeholder',title: 'Y',titlePosition: 'left',error: false,disabled: false,width: '150px',titleXs: 3,inputXs: 9,height: '30px',textAlign: 'left',multiline: false,rows: 1,maxRows: 1,gap: 1,inputAlign: 'left',singleLineTitle: false,}}>
				</Moaui.TextFieldV2>
				<Moaui.TextFieldV2 {...{id: 'input_z',autoFocus: false,type: 'text',placeholder: 'Placeholder',title: 'Z',titlePosition: 'left',error: false,disabled: false,width: '150px',titleXs: 3,inputXs: 9,height: '30px',textAlign: 'left',multiline: false,rows: 1,maxRows: 1,gap: 1,inputAlign: 'left',singleLineTitle: false,}}>
				</Moaui.TextFieldV2>
			</Moaui.FloatingBox>
			<Moaui.FloatingBox {...{x: 328,y: 0,width: 312,height: 256,guideBoxProps: {"width":"inherit","height":"inherit","center":true,"spacing":2},}}>
				<Moaui.Button {...{id: 'button_post',disabled: false,width: '100px',loading: false,variant: 'contained',color: 'normal',}}>POST</Moaui.Button>
				<Moaui.Button {...{id: 'button_put',disabled: false,width: '100px',loading: false,variant: 'contained',color: 'normal',}}>PUT</Moaui.Button>
				<Moaui.Button {...{id: 'button_delete',disabled: false,width: '100px',loading: false,variant: 'contained',color: 'normal',}}>DELETE</Moaui.Button>
				<Moaui.Button {...{id: 'button_get',disabled: false,width: '100px',loading: false,variant: 'contained',color: 'negative',}}>GET</Moaui.Button>
			</Moaui.FloatingBox>
			<Moaui.FloatingBox {...{x: 0,y: 256,width: 640,height: 384,guideBoxProps: {"width":"inherit","height":"inherit"},}}>
				<Moaui.CodeBlock {...{id: 'print_get',title: 'PRINT GET',radius: 4,width: '100%',backgroundColor: 'black',titlePadding: 1,titlePaddingX: 1,titlePaddingY: 1,codePadding: 1,codePaddingX: 1,codePaddingY: 1,language: 'json',}}>@getValues</Moaui.CodeBlock>
			</Moaui.FloatingBox>
		</Moaui.Panel>
	);
}

export default App;