// MCT Keywords and Constants

export const MCT_KEYWORDS = {
  // Basic data
  NODE: '*NODE',
  ELEMENT: '*ELEMENT',
  MATERIAL: '*MATERIAL',
  SECTION: '*SECTION',
  THICKNESS: '*THICKNESS',

  // Constraints and links
  RIGID_LINK: '*RIGIDLINK',
  CONSTRAINT: '*CONSTRAINT',

  // Hinges
  IHINGE_PROP: '*IHINGE-PROP',
  IHINGE_ASSIGN: '*IHINGE-ASSIGN',

  // Nonlinear properties
  NL_LINK: '*NL-LINK',
  NL_PROP: '*NL-PROP',

  // Springs
  GSPRING: '*GSPRING',
  GSPRTYPE: '*GSPRTYPE',

  // Mass
  NODAL_MASS: '*NODALMASS',

  // Loads
  STLDCASE: '*STLDCASE',
  CONLOAD: '*CONLOAD',
  SPDISP: '*SPDISP',
  BEAMLOAD: '*BEAMLOAD',
  ELTEMPER: '*ELTEMPER',

  // Initial forces
  INI_EFORCE: '*INI-EFORCE',

  // Section specific
  SECT_PSCVALUE: '*SECT-PSCVALUE',
} as const;

// Element types
export const ELEMENT_TYPES = {
  BEAM: 'BEAM',
  TRUSS: 'TRUSS',
  PLATE: 'PLATE',
  SOLID: 'SOLID',
} as const;

// Material types
export const MATERIAL_TYPES = {
  STEEL: 'STEEL',
  CONC: 'CONC',
  USER: 'USER',
} as const;

// Standard material codes
export const MATERIAL_STANDARDS = {
  CONCRETE: 'JIS-Civil(RC)',
  STEEL: 'JIS-Civil(S)',
} as const;

// Concrete strength mapping
export const CONCRETE_STRENGTH_MAP: Record<number, string> = {
  21: 'Fc21',
  24: 'Fc24',
  27: 'Fc27',
  30: 'Fc30',
  36: 'Fc36',
  40: 'Fc40',
  50: 'Fc50',
  60: 'Fc60',
  70: 'Fc70',
  80: 'Fc80',
};

// Steel strength mapping
export const STEEL_STRENGTH_MAP: Record<number, string> = {
  235: 'SS400',
  315: 'SM490',
  355: 'SM490Y',
  450: 'SM570',
};

// Poisson ratio defaults
export const POISSON_RATIO_MAP: Record<string, number> = {
  'コンクリート材料': 0.167,
  '鉄筋材料': 0.3,
  '鋼材料': 0.3,
  '炭素繊維シート（FRP）材料': 0.46,
};

// Material category types
export const MATERIAL_CATEGORIES = {
  CONCRETE: 'コンクリート材料',
  REINFORCEMENT: '鉄筋材料',
  STEEL: '鋼材料',
  FRP: '炭素繊維シート（FRP）材料',
} as const;

// Input types
export const INPUT_TYPES = {
  DATABASE: 'データベース',
  USER: 'ユーザー',
} as const;

// DOF (Degrees of Freedom) strings
export const DOF = {
  ALL: '111111',
  DX: '100000',
  DY: '010000',
  DZ: '001000',
  RX: '000100',
  RY: '000010',
  RZ: '000001',
} as const;

// Hinge types
export const HINGE_TYPES = {
  BILINEAR: 'BILINEAR',
  TRILINEAR: 'TRILINEAR',
  TETRALINEAR: 'TETRALINEAR',
  TAKEDA: 'TAK',
} as const;

// Spring directions
export const SPRING_DIRECTIONS = {
  XL: 'xl',
  YL: 'yl',
  ZL: 'zl',
  RXL: '回xl',
  RYL: '回yl',
  RZL: '回zl',
} as const;

// Direction component mapping (1-indexed)
export const DIRECTION_COMPONENT_MAP: Record<string, number> = {
  'xl': 1,
  'yl': 2,
  'zl': 3,
  '回xl': 4,
  '回yl': 5,
  '回zl': 6,
};

// Spring data type
export const SPRING_DATA_TYPES = {
  D_K: 'd-K',
  D_F: 'd-F',
} as const;

// Maximum name lengths
export const MAX_LENGTHS = {
  MATERIAL_NAME: 13,
  HINGE_NAME: 20,
} as const;

// MCT file header template
export const MCT_HEADER = `; MIDAS/CIVIL NX Text Data File
; Generated by ES-to-MIDAS Convertor
`;

// Unit settings
export const UNIT_SETTINGS = {
  FORCE: 'kN',
  LENGTH: 'm',
  HEAT: 'kJ',
  TEMPERATURE: 'C',
} as const;
