// VBA: src/basicVBA/bas/main.bas > mct作成()
// MCT 변환 오케스트레이터 — VBA main.bas의 실행 순서를 따름
import type { TabData, MctResult, GlobalMaps } from '../types';
import { createEmptyGlobalMaps } from '../types';
import { getNodeData, convertNodes } from './nodeConverter';
import { getSpringElemDblPnt } from './elemSpringConverter';

/**
 * 전체 MCT 변환 오케스트레이션
 * VBA main.bas의 mct作成() 서브루틴 순서를 정확히 따름
 *
 * @param tabData 모든 탭의 원시 데이터
 * @returns { mctResult: 버전별 MCT 출력, globalMaps: 최종 전역 맵 }
 */
export function orchestrate(
  tabData: TabData
): { mctResult: MctResult; globalMaps: GlobalMaps } {
  const maps = createEmptyGlobalMaps();
  const _td = tabData; // 축약

  // ══════════════════════════════════════════════
  // VBA main.bas mct作成() 호출 순서:
  // ══════════════════════════════════════════════

  // ── Phase 1: READ (데이터 읽기 & 전역 맵 구성) ──

  // 1. clsNode.GetNode(dicDblNode_Z) — 노드 데이터 읽기, dicDblNode_Z 구성
  // VBA: If ChangeSheetName.Exists(m_Sheet_Node) Then Call clsNode.GetNode(dicDblNode_Z)
  const dicDblNode_Z = _td.node.length > 0
    ? getNodeData(_td.node)
    : new Map<string, [string, string]>();
  void dicDblNode_Z; // Frame의 ReadFrame_Sectname에서 사용 예정

  // 2. clsElmSpr.GetSpringElem(dicDblPnt) — 스프링 요소에서 이중점 노드 추출
  // VBA: If ChangeSheetName.Exists(m_Sheet_ElmSpr) Then Call clsElmSpr.GetSpringElem(dicDblPnt)
  const dicDblPnt = _td.spring_elem.length > 0
    ? getSpringElemDblPnt(_td.spring_elem)
    : new Map<string, string>();

  // 3. clsNumbSect.GetNumbSect() — 미리 정의된 단면, m_Sect2Material 설정
  // TODO: processNumbSect
  void _td.numbsect;

  // ── Phase 2: FRAME & SECTION 처리 ──

  // 4. clsFrame.ReadFrame_Sectname(dicSectName) — 프레임에서 고유 단면명 수집
  // TODO: convertFrames phase 1 (ReadFrame_Sectname)

  // 5. clsSectElem.ReadSectElem_SectName() — SectElem에 있는 단면을 dicSectName에서 제거
  // TODO: processSectElem phase 1

  // 6. m_Sect2Material에 이미 있는 단면도 dicSectName에서 제거

  // 7. clsSect.ReadSect_SectName(dicSectName) — 남은 dicSectName의 Young/thermal 읽기
  // TODO: convertSect phase 1

  // ── Phase 3: CONVERT (MCT 출력 생성) ──

  // 8. clsNode.ChangeNode(dicDblPnt) — *NODE 출력
  // VBA: If ChangeSheetName.Exists(m_Sheet_Node) Then Call clsNode.ChangeNode(dicDblPnt)
  const nodeResult = _td.node.length > 0
    ? convertNodes(_td.node, dicDblPnt)
    : { lines: [], updatedMaps: {} };
  Object.assign(maps, nodeResult.updatedMaps);

  // 9. clsMaterial.ChangeMaterial(dicMatlYoung, dicSectName) — *MATERIAL 출력
  // TODO: convertMaterial

  // 10. clsFrame.ReadFrame(dicSectAll) — 모든 단면 참조 수집
  // TODO: convertFrames phase 2

  // 11. clsRigid.ReadRigid(strRigid) — 강체 데이터 읽기
  // TODO: convertRigid phase 1

  // 12. clsFrame.SetElemNo() — 요소 번호 할당
  // TODO: convertFrames phase 3

  // 13. clsSect.ChangeSect() — *SECTION, *SECT-PSCVALUE 출력
  // TODO: convertSect phase 2

  // 14. clsSectElem.ReadSectElem() — 단면 요소 처리
  // TODO: processSectElem phase 2

  // 15. clsFrame.ChangeFrame(dicHingeElem) — *ELEMENT (프레임) 출력
  // TODO: convertFrames phase 4

  // 16. clsPlnElm.ChangePlnElm() — *ELEMENT (평판) 출력
  // TODO: convertPlnElm

  // 17. clsHngPrp.ReadHinge_Prop() + ChangeHinge_Prop() — *IHINGE-PROP 출력
  // TODO: convertHingeProp

  // 18. clsHngAss.ChangeHinge_Ass() — *IHINGE-ASSIGN 출력
  // TODO: convertHingeAss

  // 19. clsRigid.ChangeRigid() — *RIGIDLINK 출력
  // TODO: convertRigid phase 2

  // 20. clsSPG6Comp.GetHingeSPG6Comp() — 스프링 데이터 사전 처리
  // TODO: processSpg6Comp

  // 21. clsElmSpr.ChangeElemSpring() — *NL-LINK 출력
  // TODO: convertElemSpring phase 2

  // 22. SPGAllSym/ASym/Other — *NL-PROP 등 스프링 특성 출력
  // TODO: convertSpgAllSym, convertSpgAllASym, convertSpgAllOther

  // 23. clsFulcrum/FulcDetail — *GSPRING, *CONSTRAINT 출력
  // TODO: convertFulcrum, convertFulcDetail

  // 24. clsNodalMass.ChangeNodalMass() — *NODAL-MASS 출력
  // TODO: convertNodalMass

  // 25. clsLoad.ChangeLoad() — *LOAD 출력
  // TODO: convertLoad

  // ── Phase 4: 조합 ──
  // 모든 섹션을 합쳐 최종 MCT 문자열 생성
  const allLines: string[] = [];

  if (nodeResult.lines.length > 0) {
    allLines.push(...nodeResult.lines);
  }

  const mctText = allLines.length > 0
    ? allLines.join('\n') + '\n'
    : '; Generated by ES→MCT Converter\n; No data to convert\n';

  return {
    mctResult: {
      v2025: mctText,
      v2026: mctText,
    },
    globalMaps: maps,
  };
}
